version: '3.8'

services:
  tinllm-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tinllm-engine
    ports:
      - "8080:8080"
    environment:
      - OMP_NUM_THREADS=8
      - DIRECT=1
      - URING=1
      - PIPE=1
    volumes:
      - ./models:/models
    restart: unless-stopped
